[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "wallet"
version = "0.0.1"
dependencies = ["peewee >= 3.17.6", "click >= 8.1.7"]

[project.scripts]
"wallet" = "wallet.main:main"
